In [1]:
from src.components.data_transformation import AvgWord2VecTransformer
import pandas as pd

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\MARK\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MARK\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\MARK\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [2]:
df = pd.read_csv('D:/PROJECTS/Spam_ham/artifact/new_raw.csv')
df.head()

message label
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham

In [3]:
import gensim

In [4]:
model = gensim.models.Word2Vec(df['message'], window=5, min_count=2)
avg = AvgWord2VecTransformer(model=model, vector_size=100)

In [7]:
x_arr = avg.transform(df['message'])

shape of output vector array: (5572, 100)


In [8]:
x_arr

array([[ 0.08156593, -0.01654109, -0.12217434, ...,  0.09169908,
        -0.31980577, -0.13389412],
       [ 0.06254326, -0.01261468, -0.07486455, ...,  0.10102341,
        -0.31125668, -0.12232729],
       [ 0.11181074, -0.04265167, -0.12990525, ...,  0.06824829,
        -0.3601083 , -0.16806786],
       ...,
       [ 0.07210715, -0.01019281, -0.09696254, ...,  0.07362017,
        -0.32245046, -0.13669261],
       [ 0.07512356,  0.00430616, -0.09476101, ...,  0.08072476,
        -0.33262372, -0.15627548],
       [ 0.10356133, -0.04289059, -0.10813075, ...,  0.08960694,
        -0.33230397, -0.18057072]], dtype=float32)

In [9]:
from sklearn.compose import ColumnTransformer

In [10]:
preprocessor = ColumnTransformer([
                ('Avg_w2v',AvgWord2VecTransformer(model=model, vector_size=100), 'message')
])

In [11]:
X = df[['message']]

In [14]:
X

message
0     ['go', 'jurong', 'point', 'crazy', 'available'...
1                 ['ok', 'lar', 'joking', 'wif', 'oni']
2     ['free', 'entry', 'wkly', 'comp', 'win', 'fa',...
3      ['dun', 'say', 'early', 'hor', 'already', 'say']
4     ['nah', 'think', 'go', 'usf', 'life', 'around'...
...                                                 ...
5567  ['nd', 'time', 'tried', 'contact', 'pound', 'p...
5568               ['going', 'esplanade', 'fr', 'home']
5569  ['pity', 'mood', 'that', 'so', 'any', 'suggest...
5570  ['guy', 'bitching', 'acted', 'like', 'interest...
5571                           ['rofl', 'true', 'name']

[5572 rows x 1 columns]

In [12]:
x_array = preprocessor.transform(X)
x_array

NotFittedError: This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [13]:
array_X = preprocessor.fit_transform(X)
array_X

shape of output vector array: (5572, 100)


array([[ 0.08156593, -0.01654109, -0.12217434, ...,  0.09169908,
        -0.31980577, -0.13389412],
       [ 0.06254326, -0.01261468, -0.07486455, ...,  0.10102341,
        -0.31125668, -0.12232729],
       [ 0.11181074, -0.04265167, -0.12990525, ...,  0.06824829,
        -0.3601083 , -0.16806786],
       ...,
       [ 0.07210715, -0.01019281, -0.09696254, ...,  0.07362017,
        -0.32245046, -0.13669261],
       [ 0.07512356,  0.00430616, -0.09476101, ...,  0.08072476,
        -0.33262372, -0.15627548],
       [ 0.10356133, -0.04289059, -0.10813075, ...,  0.08960694,
        -0.33230397, -0.18057072]], dtype=float32)

In [1]:
from src.components.data_transformation import DataTransformation

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\MARK\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MARK\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\MARK\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [2]:
data_transformation = DataTransformation()

X_arr, y_arr,_ = data_transformation.initiate_data_transformation()

<class 'list'>
5572
['go', 'jurong', 'point', 'crazy', 'available', 'bugis', 'great', 'world', 'la', 'buffet', 'cine', 'got', 'amore', 'wat']
shape of output vector array: (5572, 100)
<class 'numpy.ndarray'>
X_array shape: (5572, 100)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
<class 'numpy.ndarray'>
y_array shape: (5572,)
[0 0 1 0 0 1 0 0 1 1]


In [3]:
X_arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [1]:
int.from_bytes(b'\x01\x00\x00\x00', byteorder='little')

1

In [5]:
eds = b'\x01\x00\x00\x00'

In [6]:
dg = int.from_bytes(eds, byteorder='little')

In [7]:
dg


1